name: Deploy Production
concurrency: production

on:
  push:
    branches:
      - prod
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment: production

    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      AMPLIFY_APP_ID: ${{ secrets.AMPLIFY_APP_ID }}
      AMPLIFY_WEBHOOK: ${{ secrets.AMPLIFY_INCOMING_WEBHOOK }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: npm ci

      - name: Deploy Amplify Backend
        run: npx ampx pipeline-deploy --branch ${{ github.ref_name }} --app-id ${{ env.AMPLIFY_APP_ID }}

      - name: Build Frontend
        run: npm run build

      - name: Deploy Amplify Frontend
        run: curl -X POST -d {} ${{ env.AMPLIFY_WEBHOOK }} -H "Content-Type:application/json"
